/**
 * riskEngine.js
 *
 * Weights are loaded from pcos_derived_weights.json (generated by analyzePCOS.js).
 * Run `node analyzePCOS.js` once after placing PCOS_infertility.csv in /data.
 *
 * If the JSON hasn't been generated yet, falls back to clinically-reasoned defaults
 * so the app still works during development.
 */

const fs   = require('fs');
const path = require('path');

// ── Load derived weights (or fall back to hardcoded defaults) ─────────────
let derivedWeights = null;
let fallbackWeights = null;
let datasetMeta = null;

const weightsPath = path.join(__dirname, '..', 'pcos_derived_weights.json');

if (fs.existsSync(weightsPath)) {
  try {
    const raw = JSON.parse(fs.readFileSync(weightsPath, 'utf8'));
    derivedWeights  = raw.derivedWeights;
    fallbackWeights = raw.fallbackWeights;
    datasetMeta     = raw._meta;
    console.log(`✅ Risk engine: loaded data-derived weights (source: ${datasetMeta.source}, n=${datasetMeta.total_rows})`);
  } catch (e) {
    console.warn('⚠️  Could not parse pcos_derived_weights.json — using hardcoded defaults');
  }
}

// ── Final weight map (derived first, fallback if missing) ─────────────────
const W = {
  // ── Cycle ──────────────────────────────────────────────────────────────
  cycleGap_irregular: derivedWeights?.cycleGap_irregular ?? 30,
  cycleGap_more35:    fallbackWeights?.cycleGap_more35    ?? 25,
  cycleGap_less21:    fallbackWeights?.cycleGap_less21    ?? 15,

  // ── Physical symptoms ─────────────────────────────────────────────────
  // Derived from PCOS_infertility.csv odds ratios where available
  facial_hair:        derivedWeights?.hair_growth          ?? 25,
  skin_darkening:     derivedWeights?.skin_darkening        ?? 18,
  hair_loss:          derivedWeights?.hair_loss             ?? 14,
  weight_gain:        derivedWeights?.weight_gain           ?? 16,
  acne:               derivedWeights?.pimples               ?? 12,

  // Not in CSV → clinically-reasoned fallbacks
  clots:              fallbackWeights?.clots                ?? 20,
  heavy_flow:         fallbackWeights?.heavy_flow           ?? 15,
  spotting:           fallbackWeights?.spotting             ?? 10,
  back_pain:          fallbackWeights?.back_pain            ??  5,

  // ── Lifestyle ─────────────────────────────────────────────────────────
  // Derived (exercise inverse correlation)
  no_exercise:        derivedWeights?.no_exercise           ??  8,
  fast_food:          derivedWeights?.fast_food             ??  6,

  // Not in CSV → reasoned
  stress_very_high:   fallbackWeights?.stress_very_high     ?? 12,
  stress_high:        fallbackWeights?.stress_high          ??  8,
  diet_restricting:   fallbackWeights?.diet_restricting     ?? 10,
  diet_skipping:      fallbackWeights?.diet_skipping        ??  6,
  activity_too_tired: fallbackWeights?.activity_too_tired   ??  8,
  sleep_very_poor:    fallbackWeights?.sleep_very_poor      ??  8,
  sleep_poor:         fallbackWeights?.sleep_poor           ??  5,
};

// ── Main risk calculation ─────────────────────────────────────────────────
function calculateRisk(user) {
  let score = 0;
  const flags        = [];
  const weightTrace  = []; // for transparency / debug

  const track = (label, points) => {
    score += points;
    flags.push(label);
    weightTrace.push({ factor: label, points });
  };

  // ── Cycle gap ──────────────────────────────────────────────────────────
  if (user.cycleGap === 'irregular') {
    track('Irregular cycle length', W.cycleGap_irregular);
  } else if (user.cycleGap === 'more35') {
    track('Cycle gap over 35 days', W.cycleGap_more35);
  } else if (user.cycleGap === 'less21') {
    track('Cycle gap under 21 days', W.cycleGap_less21);
  }

  // ── Physical symptoms ──────────────────────────────────────────────────
  const physical = user.physicalSymptoms || [];

  const physicalMap = [
    { key: 'facial_hair',    weight: W.facial_hair,    label: 'Unusual hair growth (face/body)' },
    { key: 'skin_darkening', weight: W.skin_darkening, label: 'Skin darkening'                  },
    { key: 'hair_loss',      weight: W.hair_loss,      label: 'Unusual hair loss'               },
    { key: 'weight_gain',    weight: W.weight_gain,    label: 'Unexplained weight gain'         },
    { key: 'acne',           weight: W.acne,           label: 'Acne / pimples'                  },
    { key: 'clots',          weight: W.clots,          label: 'Clots in flow'                   },
    { key: 'heavy_flow',     weight: W.heavy_flow,     label: 'Heavy bleeding'                  },
    { key: 'spotting',       weight: W.spotting,       label: 'Spotting between periods'        },
    { key: 'back_pain',      weight: W.back_pain,      label: 'Back pain'                       },
  ];

  for (const s of physicalMap) {
    if (physical.includes(s.key)) track(s.label, s.weight);
  }

  // ── Lifestyle ──────────────────────────────────────────────────────────
  if (user.stressLevel   === 'very_high')   { score += W.stress_very_high;   }
  if (user.stressLevel   === 'high')        { score += W.stress_high;        }
  if (user.dietPattern   === 'restricting') { score += W.diet_restricting;   }
  if (user.dietPattern   === 'skipping')    { score += W.diet_skipping;      }
  if (user.activityLevel === 'too_tired')   { score += W.activity_too_tired; }
  if (user.activityLevel === 'no_exercise') { score += W.no_exercise;        }
  if (user.sleepPattern  === 'very_poor')   { score += W.sleep_very_poor;    }
  if (user.sleepPattern  === 'poor')        { score += W.sleep_poor;         }
  if (user.dietPattern   === 'fast_food')   { score += W.fast_food;          }

  // Cap at 100
  score = Math.min(score, 100);

  // ── Risk level ─────────────────────────────────────────────────────────
  let level, message, color;

  if (score >= 55) {
    level   = 'high';
    color   = 'red';
    message = 'Several patterns in your data are commonly associated with PCOS. We strongly recommend discussing this with a gynecologist.';
  } else if (score >= 25) {
    level   = 'moderate';
    color   = 'amber';
    message = 'Some patterns worth monitoring. Keep tracking and consider mentioning these to a doctor at your next visit.';
  } else {
    level   = 'low';
    color   = 'green';
    message = 'No strong risk indicators detected right now. Keep tracking — the more data, the clearer the picture.';
  }

  // ── Age context ────────────────────────────────────────────────────────
  let ageContext = null;

  if (user.age >= 45) {
    ageContext = {
      label:   'Perimenopause range',
      message: 'At your age, irregular cycles may be related to perimenopause — a natural transition. Discuss with your doctor to distinguish PCOS symptoms from perimenopausal changes.',
      color:   'purple',
    };
  } else if (user.age >= 40) {
    ageContext = {
      label:   'Pre-perimenopause watch',
      message: 'Hormonal shifts can begin in your 40s. Keep tracking cycle changes carefully.',
      color:   'amber',
    };
  } else if (user.age && user.age <= 17) {
    ageContext = {
      label:   'Teen cycle — irregular is normal',
      message: 'Irregular cycles are completely expected in the first 2–3 years after your first period. Most patterns shown here are normal for your age.',
      color:   'green',
    };
  }

  // ── Data source label (shown in UI for transparency) ──────────────────
  const dataSource = datasetMeta
    ? {
        label:    `Weights derived from ${datasetMeta.total_rows} patient records`,
        source:   datasetMeta.source,
        positive: datasetMeta.pcos_positive,
      }
    : { label: 'Using clinically-reasoned baseline weights (run analyzePCOS.js to derive from data)' };

  return { score, level, flags, message, color, ageContext, dataSource, weightTrace };
}

// ── Exported helpers ──────────────────────────────────────────────────────

/**
 * Returns the weight map (useful for the insights/transparency screen)
 */
function getWeights() {
  return { ...W };
}

/**
 * Returns metadata about the dataset used (for display in UI)
 */
function getDatasetMeta() {
  return datasetMeta;
}

module.exports = { calculateRisk, getWeights, getDatasetMeta };